feign:
  url:
    prefix: http://localhost:8080/target_server
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 3000
        loggerLevel: NONE
      demo-client:
        connectTimeout: 1000
        readTimeout: 10000
        loggerLevel: BASIC